version: '3.3'
services:
  back:
    image: ${PROJ_NAME}:latest
    container_name: ${PROJ_NAME}
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back/app:/home/app
      # - /home/app/node_modules
    ports:
      - ${DEV_PORT}:3000
      - ${PROD_PORT}:5000
    depends_on:
      - mysql
    tty: true
  mysql:
    image: mysql-for-express:latest
    container_name: mysql-for-express
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      # - ./mysql/db/my.cnf:/etc/mysql/my.cnf
      - ./mysql/db/mysql_conf:/etc/mysql/conf.d
      - ./mysql/db/data:/var/lib/mysql
      - ./mysql/db/log:/var/log
      - ./mysql/db/sql:/docker-entrypoint-initdb.d
    ports:
      - ${PORT_DB}:${PORT_DB}
    environment:
      MYSQL_DATABASE: 'nodejs_db'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
